version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: on-failure
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080